### ISSUE TITLE
Add multiple "<param>" children for <etc_directory> tag

### ISSUE THREAD

**Issue by nbenketaf** [qwazr/QWAZR#504]
Actually the <etc_directory> tag of the maven plugin accepts only a string.
If multiple values are provided, they must be set in the same string with a separator.

Ex:

``` xml
<plugin>
    <groupId>com.qwazr</groupId>
    <artifactId>qwazr-maven-plugin</artifactId>
    <configuration>
        <etc_directory>dir1;dir2</etc_directory>
    </configuration>
</plugin>
```

Possible enhancement:

``` xml
<plugin>
    <groupId>com.qwazr</groupId>
    <artifactId>qwazr-maven-plugin</artifactId>
    <configuration>
        <etc_directory>
            <param>dir1</param>
            <param>dir2</param>
        </etc_directory>
    </configuration>
</plugin>
```

**Comment by emmanuel-keller** [comment]
Definitely better +1.
Currently done and available in 1.0.1-SNAPSHOT.

I will also rename the properties etc_directory as etcDirectory and etc as etcFilter.
