### ISSUE TITLE
Allow static resources to be picked up either from file system or classpath

### ISSUE THREAD

**Issue by nbenketaf** [qwazr/QWAZR#616]
The `statics` entry in the qwazr config file resolves only file system path.

It could be usefull to also resolve classpath entries.

Thanks.

Nabil

**Comment by emmanuel-keller** [comment]
Done. Just use the name of the package.

```json
{
    "statics": {
         "/img/*": "org.package"
    }
}
```

[Some example from the unit tests in the source code](https://github.com/qwazr/QWAZR/qwazr-webapps/src/test/resources/com/qwazr/webapps/test/etc/webapp.json)
